### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by ahmadsghaier** [pcaversaccio/xdeployer#176]
### Describe the issue:

When deploying to Polygon mainnet contract deploy fails due to low gas limit while it has been set to the max allowed value 15e6
`{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"transaction underpriced\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\"
`
The 

### Code example to reproduce the issue:

```
xdeploy: {
    contract: 'ERC1155Factory',
    salt: 'DeploySalt',
    signer: process.env.PRIVATE_KEY,
    networks: [
      'polygon' 
  ],
    rpcUrls: [
      'https://polygon-mainnet.g.alchemy.com/v2/' + process.env.ALCHEMY_API_KEY
    ],
    gasLimit: 15_000_000 // optional; default value is `1.5e6`
  }
```

For Polygon average gaslimit reaches 30e6 so the hard limit of 15e6 might need to be updated

### Version:

1.2.7

**Comment by pcaversaccio** [comment]
@ahmadsghaier Thanks for opening this issue. I've been aware of this for many months and this is nothing I can solve on the `xdeployer` side. The main reason can be found [here](https://github.com/ethers-io/ethers.js/issues/3370#issuecomment-1409834579) (it's _not_ the `gasLimit` but the `maxPriorityFeePerGas`):

> This is a known issue with BSC/Polygon, since they do not correctly implement the EIP-1559 standard.
> 
> Unfortunately for those networks, it is necessary to use a gas station (much like Ethereum did prior to EIP-1559). There isn't really a way to get good data (especially during times of congestion) from the blockchain directly.
> 
> My best advice would be that someone creates a sub-class of Signer, and overrides the getFeeData method to use a gas station instead. This is one reason why getFeeData is present there. :)
> 
> If someone creates a sub-class of Signer, let me know and I'll link to it from the docs. But I don't know there is much that ethers can do directly.

I would like to highlight that Polygon has an enforced _minimum_ [30 gwei priority fee](https://twitter.com/pcaversaccio/status/1597365974365532160) and ethers.js currently [hardcodes](https://github.com/ethers-io/ethers.js/blob/master/packages/abstract-provider/src.ts/index.ts#L252) the priority fee, where applicable, at 1.5 gwei. That's why deployments on Polygon are failing/pending forever.

I've discussed potential solutions in [this discussion](https://github.com/pcaversaccio/xdeployer/discussions/53). Either you fork and adjust it as I describe there, or you can manually call yourself the contract using [Polygonscan](https://polygonscan.com/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2) and MetaMask. I won't build a custom solution for one particular chain, because they can't get their job done properly. All other chains work smoothly. Closing this issue as no remediation is planned.
