### ISSUE TITLE
💥 Add `seiArcticTestnet` Deployment

### ISSUE THREAD

**Issue by dangerousfood** [pcaversaccio/xdeployer#254]
### Describe the desired feature:

I have confirmed that `seiArcticTestnet` does conform to the standard `CREATE2` behavior. Would you kindly deploy to `seiArcticTestnet`?

**Comment by pcaversaccio** [comment]
Since `xdeployer` version [`3.0.0`](https://github.com/pcaversaccio/xdeployer/releases/tag/v3.0.0), the [`CreateX`](https://github.com/pcaversaccio/createx) contract factory is used which supports the `seiArcticTestnet`. I deployed the old [`Create2Deployer`](https://github.com/pcaversaccio/create2deployer) factory now also on Sei Arctic Testnet here: [`0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2`](https://seistream.app/account/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2).
